pizzeria/pizzas/urls.py
from django.conf.urls.static import static
from django.urls import path
#
# from pizzeria import settings

"""Определяет схемы URL для pizzas"""

from .views import *


app_name = 'pizzas'


urlpatterns = [
    path('', index, name='home'),
    path('pizzas/', show_pizzas, name='list_pizzas'),
    path('pizzas/<int:pizza_id>', show_one_pizza, name='pizza'),
    path('api/v1/pizza_order', PizzasViewSet.as_view({"get": "list", "post": "create"}), name='all_pizzas'),
    path('api/v1/pizza_order/<int:pk>/', PizzasViewSet.as_view({"put": "partial_update"}), name='update_pizza'),
    path('api/v1/pizza_order_delete/<int:pk>/', PizzasViewSet.as_view({"delete": "destroy"}), name='delete_pizza'),
]

pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

pizzeria/users/urls.py
from django.urls import path, include
from .views import *
app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register'),
]

pizzeria/pizzas/models.py
from django.db import models
from django.contrib.auth.models import User


class Pizza(models.Model):
    name = models.CharField(max_length=25, verbose_name="Название пиццы", db_index=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    name = models.CharField(max_length=25, verbose_name="Наполнение пиццы")
    pizza = models.ForeignKey(Pizza, default=None, on_delete=models.CASCADE, verbose_name='название пиццы', blank=True)

    def __str__(self):
        return self.name

#
class PizzaOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='id заказчика')
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE, verbose_name='название пиццы')

    def __str__(self):
        return self.pizza

pizzeria/users/models.py
from django.db import models

# Create your models here.

pizzeria/pizzas/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework import generics, viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly


from pizzas.models import *
from pizzas.serializers import *
from pizzas.permissions import *

def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'pizzas/index.html')

def show_pizzas(request):
    """Страница для отображения списка всех пицц"""
    pizz = Pizza.objects.all()
    context = {'pizza': pizz}
    return render(request, 'pizzas/pizzas.html', context=context)

def show_one_pizza(request, pizza_id):
    """Выводит 1 пиццу и все ее дополнения"""
    pizza = Pizza.objects.get(pk=pizza_id)
    names = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'names': names}
    return render(request, 'pizzas/pizza.html', context=context)


# class PizzasAPIList(generics.ListCreateAPIView):
#     queryset = Pizza.objects.all()
#     serializer_class = PizzaSerializer
#
# class PizzasAPIUpdate(generics.RetrieveUpdateDestroyAPIView):
#     queryset = Pizza.objects.all()
#     serializer_class = PizzaSerializer
#     permission_classes = (IsAuthenticatedOrReadOnly,)
#
#
# class PizzasAPIDestroy(generics.RetrieveDestroyAPIView):
#     queryset = Pizza.objects.all()
#     serializer_class = PizzaSerializer
#     permission_classes = (IsAuthenticatedOrReadOnly,)



# class PizzasAPIList(generics.ListCreateAPIView):
#     queryset = PizzaOrder.objects.all()
#     serializer_class = PizzaOrderSerializer
#
# class PizzasAPIUpdate(generics.RetrieveUpdateDestroyAPIView):
#     queryset = PizzaOrder.objects.all()
#     serializer_class = PizzaOrderSerializer
#     permission_classes = (IsOwnerOrReadOnly,)




# class PizzasAPIDestroy(generics.RetrieveDestroyAPIView):
#     queryset = PizzaOrder.objects.all()
#     serializer_class = PizzaOrderSerializer
#     permission_classes = (IsAuthenticatedOrReadOnly,)


class PizzasViewSet(viewsets.ModelViewSet):
   queryset = PizzaOrder.objects.all()
   serializer_class = PizzaOrderSerializer
   permission_classes = (IsOwnerOrReadOnly,)

pizzeria/users/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect



def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('pizzas:home')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

pizzeria/pizzas/templates/pizzas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'pizzas:home' %}">Return homepage</a> --
    <a href="{% url 'pizzas:list_pizzas' %}">Pizzas</a> --

    {% if user.is_authenticated %}
    <span>Hello, {{ user.username }}.</span>
        <a href="{% url 'users:logout' %}">Log out</a> --

    {% else %}
        <a href="{% url 'users:register' %}">Register</a> --

        <a href="{% url 'users:login' %}">Log in</a>

    {% endif %}




</p>
    {% block content %}
    {% endblock content %}

</body>
</html>

pizzeria/pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}


{% block content %}
<h3>home page pizza</h3>

{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}
 
{% block content %}
<p>Pizza: {{ pizza }}</p>
 
 <p>Additives:</p>
 <ul>
  {% for name in names %}
   <li>
    <p>{{ name.name }}</p>
   </li>
  {% empty %}
   <li>There are no entries for this pizza yet.</li>
  {% endfor %}
</ul>
{% endblock content %}

pizzeria/pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Pizzas</p>
<ul>
{% for p in pizza %}
    <li>
        <a href="{% url 'pizzas:pizza' p.id %}">{{ p }}</a>
{% empty %}
    <li>No pizza have been added yet.</li>
{% endfor %}
</ul>
{% endblock content %}